name: Hi World
 
on:

  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
   
 
 
jobs:

  hello:

    runs-on: ubuntu-latest
 
    steps:

      - name: Print Hello World

        run: echo "Hello, World!"
  new:
    runs-on: ubuntu-latest
    
    steps:

      - name: Print new page

        run: echo "new, page!" 

      - name: Print Good day

        run: echo "Good, day!" 

        
 
