name: Hi World
 
on:

  workflow_dispatch:
 
 
jobs:

  hello:

    runs-on: ubuntu-latest
 
    steps:

      - name: Print Hello World

        run: echo "Hello, World!"
  new:
    runs-on: ubuntu-latest
    
    steps:

      - name: Print new page

        run: echo "new, page!"    
 
